name: Update in html file

on:
  push:
    branches:
      - production
  schedule:
    - cron:  '*/10 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Set id and pass, Run alertme script
        run: |
          export id=${{ secrets.ID }}
          export pass=${{ secrets.PASS }}
          bash alertme.sh

      - name: setup git config
        run: |
          git config user.name "Abhay Ruparel"
          git config user.email "abhayruparel2000@gmail.com"

      - name: commit changes
        run: |
          bash commit.sh